FROM bitnami/java:11
ENV DOCKERVERSION=19.03.9
LABEL maintainer "Ryan Clair <ryan.clair@gmail.com>"

RUN install_packages git
RUN curl -fsSLO https://download.docker.com/linux/static/stable/x86_64/docker-${DOCKERVERSION}.tgz \
&& tar xzvf docker-${DOCKERVERSION}.tgz --strip 1 -C /usr/local/bin docker/docker \
&& rm docker-${DOCKERVERSION}.tgz

ENTRYPOINT ["/bin/sh"]
