FROM alpine:latest
MAINTAINER Ryan Clair <ryan.clair@gmail.com>
LABEL Description="This is a minimum Python3 image based on alpine:3"
RUN apk --update add python3 \
    && apk add py3-pip \
    && rm -f /var/cache/apk/* \
    && pip3 install --upgrade pip \
    && pip3 install --upgrade setuptools
ENTRYPOINT /bin/ash
