FROM alpine
MAINTAINER Ryan Clair <ryan.clair@emc.com>
LABEL Description="This is a minimum Python3 image"
LABEL Version="3.4"
RUN mkdir /app
WORKDIR /app
RUN apk --update add python3 && rm -f /var/cache/apk/*
RUN pip3 install --upgrade pip
RUN pip3 install --upgrade setuptools
CMD /bin/bash
