FROM ryandotclair/python
MAINTAINER Ryan Clair <ryan.clair@gmail.com>
LABEL Description="This is the collector script for SRDFA_Reporter app"
LABEL Version="1.0"
COPY ./Collector.py /app/collector.py
RUN pip3 install requests && \
  pip3 install pg8000 && \
  pip3 install APScheduler && \
  chmod a+x /app/collector.py
ENTRYPOINT ["python3", "/app/collector.py"]
